# Generated by Django 6.0.7 on 2026-07-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_telefone_alter_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('clinico_geral', 'Clínico Geral'), ('cardiologia', 'Cardiologia'), ('dermatologia', 'Dermatologia'), ('pediatria', 'Pediatria'), ('ortopedia', 'Ortopedia'), ('outro', 'Outro')], default='clinico_geral', max_length=30)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.usuario')),
            ],
            options={
                'ordering': ['data', 'hora'],
            },
        ),
    ]
